context:
  name: logistro
  version: "2.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
    sha256: 8aec9a8c5842ce649e0767c7515b8d26142a11e6732ca806de496b6e371e1f15

build:
  number: 0
  noarch: python
  script: |
    rm -rf tests
    ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-git-versioning
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - logistro
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/geopozo/logistro
  license: MIT
  license_file: LICENSE
  summary: logistro is an extremely light addition to logging, providing sensible defaults.
  repository: https://github.com/geopozo/logistro
  documentation: https://geopozo.github.io/logistro/


extra:
  recipe-maintainers:
    - ytausch
